//
// Created by lince on 11/7/20.
//

#ifndef ASYNCNET_DETAIL_CONFIG_HPP
#define ASYNCNET_DETAIL_CONFIG_HPP

#define ASYNCNET_DECL inline

#define ASYNCNET_HEADER_ONLY

#endif //ASYNCNET_DETAIL_CONFIG_HPP
